spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: file:///D:\Documents\ideaProjects\cine\cine\config-data
  security:
    user:
      name: admin
      password: 1234
server:
  port: 9000