spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: file:////D:/config/config-data
  security:
    user:
      name: admin
      password: 1234
server:
  port: 9000